#!/bin/bash
# $1 is the name of input PDF file 
# $2 is resolution of output PNG file
# $3 is the output directory
gs -dSAFER -dBATCH -dNOPAUSE -r$2 -sDEVICE=png16m -dTextAlphaBits=4 -sOutputFile=$3/page-%d.png $1 
